### PR TITLE
Skip executable directories

### LINKED ISSUE #37: Returns a directory if it is in path and executable bit is set
I ran into an issue where i had a directory in my path which contained a subdirectory. While using which to find an actual executable, it returned the path to the directory instead since it was first in the path:

```
➜  which ls -l
total 0
drwxr-xr-x  2 ptierno  staff  68 Aug 25 19:02 directory
➜  which export PATH=`pwd`:$PATH
➜  which node
> var which = require('which');
undefined
>
> which.sync('directory')
'/Users/ptierno/which/directory'                                                                                                                                                    
```

If I remove the executable bit from the directory then the directory doesnt get returned (which is what I would expect).

```
➜  which chmod -x directory
➜  which node
> var which = require('which');
undefined
> which.sync('directory')
Error: not found: directory
    at getNotFoundError (/Users/ptierno/node_modules/which/which.js:14:12)
    at Function.whichSync [as sync] (/Users/ptierno/node_modules/which/which.js:132:9)
    at repl:1:7
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
>
```

Might be a good idea to do a check to ensure the value being returned is an actual executable file and not a directory.

### PR DESCRIPTION
**Pull request by Naddiseo**
This commit fixes #37, it ignores directories from consideration.

It also adds a dependency on [is-directory](https://github.com/jonschlinkert/is-directory); I can remove this if needed.

The added test seems to break because of issue #45, I'm not sure how to fix it.

### CODE REVIEW

**Comment by Naddiseo** [comment]
This is still a WIP, I'm investigating a potential bug in is-directory, and maybe even node/fs

**Comment by iarna** [comment]
This seems like a reasonable change, but I'd prefer that we don't add a second `stat` call if we can avoid it. I wonder if patching [`isexe`](https://github.com/isaacs/isexe) would be more appropriate? 

While the implementation of `isexe` on Unix is to check the exec bit (or check `X_OK` with `fs.access`) that doesn't actually align with what it does on Windows, which is look for specific extensions. That latter behavior (plus the docs) tell me that `isexe` is supposed to be determining if a file is a thing you can execute, and in that case the logic you're adding definitely belongs there.

**Comment by Naddiseo** [comment]
I agree.
I'll patch `isexe`, and if it's accepted, I'll update this PR to update `package.json`

**Comment by isaacs** [comment]
Yeah, it looks like the only way around this is to make `isexe` always use stat/mode checking, because `access(2)` doesn't discriminate between dirs and files.

**Pull request closed without merging**
