### PR TITLE
Rename which to node-which

### PR DESCRIPTION
**Pull request by radar**
Naming the executable of this library `which` can cause issues -- such as https://github.com/microsoft/vscode/pull/82552. 

I would like to suggest renaming this executable to `node-which`, so that people can clearly differentiate between built-in `which` (bash, zsh, etc) and the Node version.

### CODE REVIEW

**Comment by isaacs** [comment]
I'm open to it.  Need to also change the `package.json` file.

**Comment by radar** [comment]
Thanks for being open to it! I've just changed `package.json`.

**Comment by radar** [comment]
@isaacs is there anything else that I need to do for this PR?

**Comment by a2425rdl** [comment]
usage: k

**Pull request closed without merging**
